

while True:
    print("o0o                              #")
    print("# o0o                            #")
    print("# o0o                            #")
    print("#  o0o                           #")
    print("#  o0o                           #")
    print("#   o0o                          #")
    print("#   o0o                          #")
    print("#     o0o                        #")
    print("#     o0o                        #")
    print("#       o0o                      #")
    print("#       o0o                      #")
    print("#         o0o                    #")
    print("#         o0o                    #")
    print("#           o0o                  #")
    print("#           o0o                  #")
    print("#             o0o                #")
    print("#             o0o                #")
    print("#               o0o              #")
    print("#               o0o              #")
    print("#                 o0o            #")
    print("#                 o0o            #")
    print("#                   o0o          #")
    print("#                   o0o          #")
    print("#                     o0o        #")
    print("#                     o0o        #")
    print("#                       o0o      #")
    print("#                       o0o      #")
    print("#                         o0o    #")
    print("#                         o0o    #")
    print("#                           o0o  #")
    print("#                            o0o #")
    print("#                           o0o  #")
    print("#                         o0o    #")
    print("#                         o0o    #")
    print("#                        o0o     #")
    print("#                        o0o     #")
    print("#                      o0o       #")
    print("#                      o0o       #")
    print("#                    o0o         #")
    print("#                    o0o         #")
    print("#                  o0o           #")
    print("#                  o0o           #")
    print("#                o0o             #")
    print("#                o0o             #")
    print("#              o0o               #")
    print("#              o0o               #")
    print("#            o0o                 #")
    print("#            o0o                 #")
    print("#          o0o                   #")
    print("#          o0o                   #")
    print("#        o0o                     #")
    print("#        o0o                     #")
    print("#      o0o                       #")
    print("#      o0o                       #")
    print("#   o0o                          #")
    print("#   o0o                          #")
    print("# o0o                            #")
    print("o0o                              #")





